---
# we rsync binaries.tar.gz from the same server we deploy to.
# it contains these static-pie binaries:
# hugo, brotli, ect (like gzip/zopfli), and xmllint.
image: alpine/edge
packages:
  - curl # Fetches webmentions and webring links. Pre-inistalled.
  - rsync
  - git  # Powers Hugo's gitInfo. Pre-installed
  - bmake # gmake is fine too
sources:
  - https://git.sr.ht/~seirdy/seirdy.one
secrets:
  - cc1eb90c-b07b-4c46-86d4-58fec41cf0e4 # ssh key
  - b0bfa66e-3cf2-468f-9ea4-085819eccd18 # webmentiond key
triggers:
  - action: email
    condition: always
    to: seirdy@seirdy.one
tasks:
  - deps: |
      sh seirdy.one/scripts/setup-ci.sh
  - build_deploy: |
      export PATH=~/bin:$PATH
      cd seirdy.one
      bmake ci
