---
# we rsync binaries.tar.gz from the same server we deploy to.
# it contains these static-pie binaries:
# hugo, brotli, ect (like gzip/zopfli), sd, htmlq (like jq for html), and xmllint.
image: alpine/edge
packages:
  - curl # for webring update script, pre-installed on builds.sr.ht images
  - rsync
  - git  # for Hugo's gitInfo, pre-installed on builds.sr.ht images
  - bmake
sources:
  - https://git.sr.ht/~seirdy/seirdy.one
secrets:
  - cc1eb90c-b07b-4c46-86d4-58fec41cf0e4 # ssh key
  - b0bfa66e-3cf2-468f-9ea4-085819eccd18 # webmentiond key
triggers:
  - action: email
    condition: always
    to: seirdy@seirdy.one
tasks:
  - deps: |
      printf "VerifyHostKeyDNS=yes\nKexAlgorithms=sntrup761x25519-sha512@openssh.com\n" >> ~/.ssh/config
      # mirrored at https://seirdy.one/misc/binaries.tar.gz
      rsync -Wv deploy@seirdy.one:/home/deploy/binaries.tar.gz .
      mkdir -p ~/bin
      tar xzf binaries.tar.gz -oC ~/bin
  - build_deploy: |
      cd seirdy.one
      export PATH=~/bin:$PATH
      # quick health + ip check
      curl -6 --proto "=https" --proto-default https --http2 -siSL --tlsv1.3 --cert-status 'seirdy.one/ip'
      echo
      curl -4 --proto "=https" --proto-default https --http2 -sSL --tlsv1.3 --cert-status 'seirdy.one/ip'
      echo
      bmake deploy-prod deploy-onion
