---
image: alpine/edge
packages:
  - rsync
  - hugo
  - zopfli
sources:
  - https://git.sr.ht/~seirdy/seirdy.one
secrets:
  - cc1eb90c-b07b-4c46-86d4-58fec41cf0e4
triggers:
  - action: email
    condition: always
    to: seirdy@seirdy.one
tasks:
  - build: |
      cd seirdy.one
      hugo
  - upload: |
      cd seirdy.one
      echo "StrictHostKeyChecking=no" >> ~/.ssh/config
      sh ./deploy.sh seirdy.one
