---
# we rsync binaries.tar.gz from the same server we deploy to.
# it contains these static-pie binaries:
# hugo, brotli, ect (like gzip/zopfli), sd, and xmlfmt.
image: alpine/edge
packages:
  - rsync
  - git  # for Hugo's gitInfo
  - bmake
  - moreutils
sources:
  - https://git.sr.ht/~seirdy/seirdy.one
secrets:
  - cc1eb90c-b07b-4c46-86d4-58fec41cf0e4
triggers:
  - action: email
    condition: always
    to: seirdy@seirdy.one
tasks:
  - deps: |
      echo "StrictHostKeyChecking=no" >> ~/.ssh/config
      rsync -Wv deploy@seirdy.one:/home/deploy/binaries.tar.gz .
      mkdir -p ~/bin
      tar xzf binaries.tar.gz -oC ~/bin
  - build_deploy: |
      cd seirdy.one
      export PATH=~/bin:$PATH
      bmake deploy-prod deploy-onion
