---
image: alpine/edge
packages:
  - rsync
  - git  # for Hugo's gitInfo
  - make
  - jq
sources:
  - https://git.sr.ht/~seirdy/seirdy.one
secrets:
  - cc1eb90c-b07b-4c46-86d4-58fec41cf0e4
triggers:
  - action: email
    condition: always
    to: seirdy@seirdy.one
tasks:
  - deps: |
      echo "StrictHostKeyChecking=no" >> ~/.ssh/config
      rsync -v deploy@seirdy.one:/home/deploy/binaries.tar.gz .
      mkdir -p ~/bin
      tar xzf binaries.tar.gz -oC ~/bin
      cd seirdy.one
  - build_deploy: |
      cd seirdy.one
      export PATH=~/bin:$PATH
      make clean deploy
      make WWW_ROOT=/var/www/seirdy.onion HUGO_BASEURL='http://wgq3bd2kqoybhstp77i3wrzbfnsyd27wt34psaja4grqiezqircorkyd.onion/' clean deploy-html
