---
image: alpine/edge
packages:
  - rsync
  - zopfli  # for max compression w/ gzip_static
  - brotli  # for max compression w/ brotli_static, decompressing binaries
  - git  # for Hugo's gitInfo
  - make
  - jq
  - npm  # for testing with lighthouse and webhint
  - chromium  # for testing with lighthouse and webhint
environment:
  HINT_TELEMETRY: "off"
sources:
  - https://git.sr.ht/~seirdy/seirdy.one
secrets:
  - cc1eb90c-b07b-4c46-86d4-58fec41cf0e4
triggers:
  - action: email
    condition: always
    to: seirdy@seirdy.one
tasks:
  - deps: |
      echo "StrictHostKeyChecking=no" >> ~/.ssh/config
      rsync deploy@seirdy.one:/home/deploy/binaries.tar.br .
      mkdir -p ~/bin
      brotli -dc binaries.tar.br | tar x -oC ~/bin
      cd seirdy.one
      npm i -D --no-fund  # no-fund reduces log verbosity
  - build_deploy: |
      cd seirdy.one
      export PATH=~/bin:$PATH
      # don't spend as much time compressing for staging.
      make DOMAIN=staging.seirdy.one ZOPFLI_ITERATIONS=50 test-staging
      tar czf ~/lighthouse-reports.tar.gz lighthouse-reports
      make clean deploy
      cp mentions.json ~/mentions.json
artifacts:
  - lighthouse-reports.tar.gz
  - mentions.json
