---
image: alpine/edge
packages:
  - rsync
  - zopfli
  - git  # for Hugo's gitInfo
  - make
  - npm
  - chromium
sources:
  - https://git.sr.ht/~seirdy/seirdy.one
secrets:
  - cc1eb90c-b07b-4c46-86d4-58fec41cf0e4
triggers:
  - action: email
    condition: always
    to: seirdy@seirdy.one
tasks:
  - deps: |
      echo "StrictHostKeyChecking=no" >> ~/.ssh/config
      rsync deploy@seirdy.one:/home/deploy/binaries.tar.gz .
      tar x -ozC /bin -f binaries.tar.gz
      npm i -g npm pnpm
      pnpm i -g @lhci/cli hint @hint/configuration-web-recommended @hint/hint-doctype @hint/hint-https-only @hint/hint-performance-budget @hint/formatter-codeframe
  - build_deploy: |
      cd seirdy.one
      make DOMAIN=staging.seirdy.one test-staging
      make clean deploy
