---
image: alpine/edge
packages:
  - rsync
  - zopfli
  - git  # for Hugo's gitInfo
  - make
  - npm  # for testing with lighthouse and webhint
  - chromium  # for testing with lighthouse and webhint
environment:
  HINT_TELEMETRY: off
sources:
  - https://git.sr.ht/~seirdy/seirdy.one
secrets:
  - cc1eb90c-b07b-4c46-86d4-58fec41cf0e4
triggers:
  - action: email
    condition: always
    to: seirdy@seirdy.one
tasks:
  - deps: |
      echo "StrictHostKeyChecking=no" >> ~/.ssh/config
      rsync deploy@seirdy.one:/home/deploy/binaries.tar.gz .
      mkdir -p ~/bin
      tar x -ozC ~/bin -f binaries.tar.gz
      cd seirdy.one
      npm i -D
  - build_deploy: |
      cd seirdy.one
      export PATH=~/bin:$PATH
      make DOMAIN=staging.seirdy.one test-staging
      tar czf ~/lighthouse-reports.tar.gz lighthouse-reports
      make clean deploy
artifacts:
  - lighthouse-reports.tar.gz
