baseURL = "https://seirdy.one/"
languageCode = "en-us"
title = "Seirdy's Home"
theme = "etch-custom"

enableInlineShortcodes = true
enableGitInfo = true
disableHugoGeneratorInject = true  # I inject it explicitly at the BOTTOM of <head>
uglyurls = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
description = "Seirdy's Home: personal website and blog for Rohan Kumar, A.K.A. Seirdy"
src = "https://sr.ht/~seirdy/seirdy.one"
logUrlPrefix = "https://git.sr.ht/~seirdy/seirdy.one/log/master/item/"
copyright = "Copyright © 2020 Rohan Kumar"
dark = "auto"
highlight = false

[author]
name = "Rohan Kumar"

[menu]
  [[menu.main]]
	identifier = "posts"
	name = "posts"
	title = "posts"
	url = "/posts.html"
	weight = 10

  [[menu.main]]
	identifier = "about"
	name = "about"
	title = "about"
	url = "/about.html"
	weight = 20

  [[menu.main]]
	identifier = "rss"
	name = "rss"
	title = "rss"
	url = "/posts/index.xml"
	weight = 30

[permalinks]
posts = "/:year/:month/:day/:filename"

[markup.goldmark.renderer]
# Allows HTML in Markdown
unsafe = true

[markup.tableOfContents]
ordered = true

# lifted from https://git.sr.ht/~sircmpwn/drewdevault.com
[mediaTypes]
[mediaTypes."text/gemini"]
suffixes = ["gmi"]

[outputFormats]
[outputFormats.Gemini]
name = "GEMTEXT"
isPlainText = true
isHTML = false
mediaType = "text/gemini"
protocol = "gemini://"
permalinkable = true
path = "gemini/"

[outputFormats.GEMRSS]
name = "GEMRSS"
isHTML = false
mediaType = "application/rss+xml"
protocol = "gemini://"
path = "gemini/"

[outputs]
section = ["HTML", "RSS", "GEMRSS"]

[server]
[[server.headers]]
for = "/**.{css,png,webp,webm}"
[server.headers.values]
X-Content-Type-Options = "nosniff"
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
Cache-Control = "max-age=31557600, immutable"
[[server.headers]]
for = "/**"
[server.headers.values]
X-Content-Type-Options = "nosniff"
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
Referrer-Policy = "no-referrer"
X-XSS-Protection = "1; mode=block"
X-FROG-UNSAFE = "1"
X-UA-Compatible = "IE=edge"
Content-Security-Policy = "default-src 'none'; img-src 'self' https://seirdy.one; style-src 'self'; script-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'; manifest-src 'self'; upgrade-insecure-requests;"
Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"
Cache-Control = "max-age=120, no-transform"
